# Generated by Django 2.2.14 on 2020-07-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(max_length=100, verbose_name='Date')),
                ('man', models.CharField(max_length=50, verbose_name='Man')),
                ('girl', models.CharField(max_length=50, verbose_name='Girl')),
                ('partner', models.CharField(max_length=50, verbose_name='Partner')),
                ('partner_get', models.CharField(max_length=10, verbose_name='Partner_get')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('comment', models.CharField(max_length=100, verbose_name='Comment')),
            ],
        ),
    ]
