# Generated by Django 2.2.14 on 2020-07-05 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20200705_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stats',
            options={'verbose_name': 'Запись статистики', 'verbose_name_plural': 'Статистика'},
        ),
    ]
